# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Chatbash release

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o chatbash && tar -zcvf chatbash_linux.tar.gz chatbash && rm -rf chatbash
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o chatbash && tar -zcvf chatbash_darwin.tar.gz chatbash && rm -rf chatbash
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o chatbash && tar -zcvf chatbash_darwin_arm.tar.gz chatbash && rm -rf chatbash

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            chatbash_linux.tar.gz
            chatbash_darwin.tar.gz
            chatbash_darwin_arm.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
